CREATE OR REPLACE PROCEDURE CLOB_PRINT (IDENTIFICADOR NUMBER)
IS
 myStoryBuf VARCHAR2(4001);
BEGIN
    SELECT D.DESCRIPCION INTO myStoryBuf FROM DESTINOS D WHERE D.ID = IDENTIFICADOR;
    DBMS_OUTPUT.PUT_LINE(myStoryBuf);
END;
/

EXECUTE CLOB_PRINT(2);